DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS ADMIN;
DROP TABLE IF EXISTS UTILISATEUR;
DROP TABLE IF EXISTS UTILISATEUR_TMP;
DROP TABLE IF EXISTS PLACE;

CREATE TABLE PLACE
(id INT(3) AUTO_INCREMENT NOT NULL,
etat boolean,
CONSTRAINT PK_PLA PRIMARY KEY(id)
)ENGINE=InnoDB;



CREATE TABLE UTILISATEUR_TMP(
id INT(3) AUTO_INCREMENT NOT NULL,
nom VARCHAR(25),
prenom VARCHAR(25),
adresse VARCHAR(25),
cp VARCHAR(5),
ville VARCHAR(25),
CONSTRAINT PK_TMP PRIMARY KEY(id)
)ENGINE=InnoDB;


CREATE TABLE UTILISATEUR(
id INT(3) AUTO_INCREMENT NOT NULL,
nom VARCHAR(25),
prenom VARCHAR(25),
adresse VARCHAR(25),
cp VARCHAR(5),
ville VARCHAR(25),
login VARCHAR(30),
mdp VARCHAR(25),
etat boolean,
CONSTRAINT PK_UTI PRIMARY KEY(id)
)ENGINE=InnoDB;



CREATE TABLE ADMIN(
id INT(3) NOT NULL,
CONSTRAINT PK_ADM PRIMARY KEY(id),
CONSTRAINT FK_ADM_UTI FOREIGN KEY(id) REFERENCES UTILISATEUR(id)
)ENGINE=InnoDB;



CREATE TABLE RESERVATION(
id_util INT(3) NOT NULL,
id_place INT(3) NOT NULL,
date_debut DATE,
date_fin DATE,
CONSTRAINT PK_RES PRIMARY KEY(id_util, id_place, date_debut),
CONSTRAINT FK_RES_UTIL FOREIGN KEY (id_util) REFERENCES UTILISATEUR(id),
CONSTRAINT FK_RES_PLA FOREIGN KEY (id_place) REFERENCES PLACE(id)
)ENGINE=InnoDB;